SELECT SALE_YM 
, SUM(CASE WHEN GOODS_CD = '0001' THEN SALE_CNT ELSE 0 END ) AS GOODS1
, SUM(CASE WHEN GOODS_CD = '0002' THEN SALE_CNT ELSE 0 END ) AS GOODS2
, SUM(CASE WHEN GOODS_CD = '0003' THEN SALE_CNT ELSE 0 END ) AS GOODS3
, SUM(CASE WHEN GOODS_CD = '0004' THEN SALE_CNT ELSE 0 END ) AS GOODS4
, SUM(CASE WHEN GOODS_CD = '0005' THEN SALE_CNT ELSE 0 END ) AS GOODS5
, SUM(SALE_CNT)
FROM KKB_GOODS_S 
GROUP BY SALE_YM 
ORDER BY SALE_YM ASC