SELECT 
B.*
, A.TX_AF_BAL
 FROM KKB_ACNO_TX A, 
(
SELECT ACNO , TX_DT,  MAX(TX_SEQ) AS TX_SEQ FROM KKB_ACNO_TX -- 마지막 회차를 품은 테이블 조회
GROUP BY ACNO , TX_DT 
) B
WHERE 1=1
-- 마지막 회차와 셀프조인
AND A.ACNO = B.ACNO
AND A.TX_DT = B.TX_DT
AND A.TX_SEQ = B.TX_SEQ
ORDER BY B.ACNO ASC, B.TX_DT ASC